### ISSUE TITLE
Crash when placing Walls

### ISSUE THREAD

**Issue by Thiana** [UnwrittenFun/WallTeleporters#1]
Hi,

Using the 1.0.0 versions of Wall Teleporters and CommonFun the game crashes instantly when you place one wall on top of another. Crash Log is available at http://pastebin.com/UtEuSw4j.

I'm using a custom modpack built on the Curse Voice launcher.

Thanks.

**Comment by jamesbirtles** [comment]
Ah yes missed this one, fix coming in a minute

**Comment by jamesbirtles** [comment]
Fix submitted to curseforge, waiting for approval

**Comment by jamesbirtles** [comment]
and its approved

**Comment by Thiana** [comment]
And it works perfectly :) I can finally build the tardis I've had in mind since 1.6.4. Thank you :)

**Comment by jamesbirtles** [comment]
awesome :D
