### ISSUE TITLE
Configurable Fuel Costs

### ISSUE THREAD

**Issue by Thiana** [UnwrittenFun/WallTeleporters#2]
A minor feature request. Could you please make the fuel costs configurable, for the tardis build I'm planning I'll probably need to hook the portals into a creative supply of the ender dust. Doable but not ideal. Thanks.

**Comment by jamesbirtles** [comment]
Sure I'll get that in probably tomorrow

**Comment by jamesbirtles** [comment]
Config option available in 1.0.2
